spring.application.name=shipping-2.0
spring.datasource.url=jdbc:postgresql://localhost:5432/shipping_db
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true